/*
===============================================================================
Magnitude Analysis
===============================================================================


    - To quantify data and group results by specific dimensions.
    -  data distribution across categories.
*/
SELECT TOP 10 * FROM gold.dim_customers

-- Find total customers by countries
SELECT 
COUNT ( DISTINCT customer_key) AS total_customers,
country 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
-- Find total customers by gender
SELECT 
COUNT(customer_key) AS total_customers,
Gender
FROM gold.dim_customers
GROUP BY Gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?

SELECT 
SUM(f.sales_amount) AS total_revenu,
c.customer_key,
c.First_name,
c.Last_name
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
GROUP BY
c.customer_key,
c.First_name,
c.Last_name
ORDER BY total_revenu DESC

-- What is the distribution of sold products across countries?

SELECT 
c.Country AS Countries,
COUNT(DISTINCT f.product_key) AS total_number_of_sold_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
GROUP BY c.Country 
ORDER BY c.Country
